Added ability to pickle FilePreference in Django 4.2
agateblue/django-dynamic-preferences pull request #297
Opened 2023-06-19 11:28 UTC by mihalikv

If you have Django 4.2 and latest django-dynamic-preferences==1.15.0 and you try to do something like this:

```
import pickle
from dynamic_preferences.types import  FilePreference
from dynamic_preferences.registries import global_preferences_registry

global_preferences = global_preferences_registry.manager()

@register_preference
class AllCategoryImage(FilePreference):
    name = 'all_category_image'
    verbose_name = 'Header image for catalog'

item = global_preferences['catalog__all_category_image']
pickled_result = pickle.dumps(item)
```

It will result in the error `AttributeError: Can't pickle local object 'PreferenceFieldFile.__init__.<locals>.FakeInstance'`

It worked well with Django 2.x but in newer Django also `field`  and `instance` attributes are added to `__setstate__` -> https://github.com/django/django/commit/f600e3fad6e92d9fe1ad8b351dc8446415f24345

2023-06-20 09:56 UTC, agateblue requested changes

2023-06-20 09:56 UTC, agateblue commented on dynamic_preferences/serializers.py
> +        return os.path.join(self.preference.get_upload_path(), f.name)
I think this line will crash : since the code was woved outside the `__init__` function, `self` isn't defined here. The tests seem to pass though, meaning we have a hole in our coverage.

Just to be sure I understand your patch: moving the code outside the `__init__` allows pickle to work because the class isn't defined at runtime, is that right?

2023-06-20 10:01 UTC, mihalikv commented on dynamic_preferences/serializers.py
> +        return os.path.join(self.preference.get_upload_path(), f.name)
Ahh, sorry my bad, I will look into it. Exactly, pickle works only on "classes accessible from the top level of a module;" see https://docs.python.org/3/library/pickle.html#what-can-be-pickled-and-unpickled

There is no test for FilePreference and I do not add new, because it looks like Django is not set-up in test cases.

2023-06-20 10:09 UTC, agateblue commented on dynamic_preferences/serializers.py
> +        return os.path.join(self.preference.get_upload_path(), f.name)
> Ahh, sorry my bad, I will look into it. Exactly, pickle works only on "classes accessible from the top level of a module;" see https://docs.python.org/3/library/pickle.html#what-can-be-pickled-and-unpickled

Thank you for the clarification! I think a workaround could be to add an `__init__` method to `FakeField` and pass it the PreferenceFieldFile instance on line 313, so it can be accessed later in `generate_filename`.

> There is no test for FilePreference and I do not add new, because it looks like Django is not set-up in test cases.

Indeed, the tests at https://github.com/agateblue/django-dynamic-preferences/blob/develop/tests/test_types.py are focusing on the low level parts and django isn't set up. If you feel like it, you can add a couple at https://github.com/agateblue/django-dynamic-preferences/blob/develop/tests/test_preferences.py

I think one for your fix / pickling would be great, to ensure we don't break this again in the future. Only if you feel like it, a basic test for the file preference (attaching a file to a preference, saving, checking that the file content / name are good) could also be added here, but I can also do it myself another time.

2023-06-21 21:05 UTC, mihalikv commented on dynamic_preferences/serializers.py
> +        return os.path.join(self.preference.get_upload_path(), f.name)
I've added a test for pickle, but I am not sure, what is the purpose of the whole `generate_filename`, do you have some idea? I would like to add a test also for that, but I am not sure why we need that. 

Thanks.

2023-06-21 21:05 UTC, mihalikv commented on dynamic_preferences/serializers.py
> +        return os.path.join(self.preference.get_upload_path(), f.name)
Currently I just remove that function and all tests are working :/

2023-06-21 21:10 UTC, mihalikv commented on dynamic_preferences/serializers.py
> +        return os.path.join(self.preference.get_upload_path(), f.name)
And one more gotcha, even in the previous method was a bug, actually from the beginning 
https://github.com/agateblue/django-dynamic-preferences/commit/dc9f677843b116df27a30f22284787d2b2bcf6bc#diff-a6a0431c6c2b29d0050a839b3febb65db74edfbbe8923fd20fe60121a071db69R244 

There is no variable `f.name` -> it should be probably `field.name`. So maybe it was never used.

2023-06-22 13:43 UTC, agateblue commented on dynamic_preferences/serializers.py
> +        return os.path.join(self.preference.get_upload_path(), f.name)
Thank you for taking the time to dig into this! I assume the whole `generate_filename` stuff was related to some things in django 1 which might have changed since. The project is quite old and I've lost memory of why I did this.

If you can confirm me you have tested locally that file preferrences work (e.g by declaring one and uploading a file through the admin), I'm happy to merge your patch in its current state.

2023-06-22 13:51 UTC, mihalikv commented on dynamic_preferences/serializers.py
> +        return os.path.join(self.preference.get_upload_path(), f.name)
Truthfully I relied on tests and I didn't try that, I will give it a try today and let you know.
Thanks.

2023-06-28 17:09 UTC, mihalikv commented on dynamic_preferences/serializers.py
> +        return os.path.join(self.preference.get_upload_path(), f.name)
@agateblue Tested locally, it works fine. 
![image](https://github.com/agateblue/django-dynamic-preferences/assets/10236315/22785cb7-f363-487e-8447-c100aec959be)

2023-06-30 14:21 UTC, mihalikv commented on dynamic_preferences/serializers.py
> +        return os.path.join(self.preference.get_upload_path(), f.name)
@agateblue  what do you think about that ?

2023-07-03 11:34 UTC, agateblue commented on dynamic_preferences/serializers.py
> +        return os.path.join(self.preference.get_upload_path(), f.name)
Perfect, thank you for taking the time, let's merge :)

2023-07-03 11:35 UTC, agateblue approved these changes

2023-07-03 11:35 UTC, merged